---

- name: install apache2
  apt:
    name:
      - "{{ apache_package }}"
    state: present

- name: enable mod_ssl
  apache2_module:
    name: ssl
    state: "{{ 'present' if apache_enable_ssl else 'absent' }}"
