---

- name: install httpd
  yum:
    name:
      - "{{ apache_package }}"
    state: present

- name: install mod_ssl
  yum:
    name:
      - mod_ssl
    state: "{{ 'present' if apache_enable_ssl else 'absent' }}"


- name: install epel
  yum: name=epel-release state=present

- name: install letsencrypt bot
  yum:
    name:
      - certbot
      - python2-certbot-apache
    state: "{{ 'present' if apache_use_letsencrypt else 'absent' }}"
