---

- name: Converge
  hosts: all
  pre_tasks:
  - name: update package repository (Debian)
    apt: update_cache=true
    when: ansible_os_family == "Debian"
  - name: update package repository (Red Hat)
    yum: update_cache=true
    when: ansible_os_family == "RedHat"
  - name: install netstat (Debian/Red Hat)
    package: name=net-tools state=present
    when: >
      ansible_os_family == "Debian" or
      ansible_os_family == "RedHat"
  vars:
    ssl_certs_certs:
      - name: instance
  roles:
    - role: ansible-role-apache
